services:
  web-admin:
    build:
      context: ./adminpanel
      dockerfile: Dockerfile
    ports:
      - "3001:80"
    depends_on:
      - backend
  web-commercial:
    build:
      context: ./foodies
      dockerfile: Dockerfile
    ports:
      - "3002:80"
    depends_on:
     - backend

  backend:   
    build:
      context: ./foodiesapi
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb+srv://sa:12345@foodies.tcalh1g.mongodb.net/foodies?retryWrites=true&w=majority
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: sa
      MONGO_INITDB_ROOT_PASSWORD: 12345
      ONGO_INITDB_DATABASE: foodies
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_data: